In [11]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [12]:
import numpy as np

In [ ]:
#Exercice 1
import numpy as np

array = array_1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print()


In [ ]:
#Exercice 2
import numpy as np

list = [3.14, 2.17, 0, 1, 2]
array =  np.array(list, dtype=int)
print(array)

[3 2 0 1 2]


In [ ]:
#Exercice 3
import numpy as np
array = np.arange(1,10).reshape(3,3)
print(array)



[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#Exercice 4
import numpy as np
# Create the 2D array
array = arr = np.random.rand(4, 5)
# Print shape and array
print("Shape of array:", arr.shape)
print("Array contents:\n", arr)


Shape of array: (4, 5)
Array contents:
 [[0.50973717 0.07306079 0.1415564  0.41370943 0.87112042]
 [0.83569048 0.25487184 0.30212498 0.11805819 0.59666074]
 [0.21778409 0.77864885 0.80633882 0.55128029 0.25153274]
 [0.06130548 0.12458509 0.23056535 0.80202524 0.89446554]]


In [ ]:
#Exercice 5
import numpy as np
array = np.array([[21, 22, 23, 22, 22],
                    [20, 21, 22, 23, 24],
                    [21, 22, 23, 22, 22]])

second_row = array[1]
print(second_row)
#In NumPy, indexing starts from 0, so array[1] refers to the second row.


[20 21 22 23 24]


In [ ]:
#Exercice 6
import numpy as np
arr = array = np.array([[0, 1, 2, 3, 4, 5,6,7,8,9]])
arr = np.arange(10)                
reversed_arr = arr[::-1]
print(reversed_arr)

[9 8 7 6 5 4 3 2 1 0]


In [ ]:
#Exercice 7
import numpy as np
# create a 4x4 identity matrix using NummPy's ny.eyes :

identity_matrix = np.eye(4)

print(identity_matrix)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [21]:
#Exercice 8
import numpy as np
arr = array = np.array([[0, 1, 2, 3, 4, 5,6,7,8,9]])
total = np.sum(arr)
average = np.mean(array)

print(total)
print(average)

45
4.5


In [23]:
#Exercice 9
import numpy as np
arr = np.arange(1, 21)
print(arr)
matrix_4x5 = arr.reshape(4, 5)

print(matrix_4x5)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [24]:
#Exercice 10
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

odd_numbers = arr[arr % 2 == 1]
print(odd_numbers)

[1 3 5 7 9]
