<a href="https://colab.research.google.com/github/arquansa/PSTB-exercises/blob/main/Week04/Day1/EX1/W4D1EXN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Exercises XP Ninja
Last Updated: November 20th, 2024

👩‍🏫 👩🏿‍🏫 What You’ll learn
How to manipulate matrices and find commonalities in data sets using NumPy.
Advanced array operations like maximum value replacement and common value identification.


🛠️ What you will create
A set of challenging exercises that include replacing the maximum value in a matrix and finding common values between arrays.


Exercise 1 : Maximum Value Replacement in Matrix
Instructions
Create a random 5x5 matrix and replace the maximum value by 0.

Expected Output:



array([[0.23, 0.35, 0.01, 0.05, 0.11],
       [0.91, 0.28, 0.66, 0.13, 0.14],
       [0.94, 0.40, 0.76, 0.65, 0.46],
       [0.12, 0.15, 0.95, 0.57, 0.60],
       [0.17, 0.97, 0.87, 0.45, 0.  ]])


Exercise 2 : Finding Common Values in Arrays
Instructions
Find the common values between two random arrays of size 5.

Expected Output:



array([0.35, 0.66, 0.76])


Exercise 3 : Sorting Array in Ascending and Descending Order
Instructions
Create a random 1D array of size 10 and sort it in ascending and then in descending order.

Expected Output:



Ascending: array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])
Descending: array([1. , 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1])


Brief Introduction to Matrix Rank
What is Matrix Rank?

The rank of a matrix indicates the number of linearly independent rows or columns in the matrix.
For example, in a matrix with rows [1, 2, 3] and [2, 4, 6], the second row is just twice the first, so these two rows are not independent. This matrix would have a rank of 1.
Why and When to Use Matrix Rank?

Matrix rank is used to determine if a set of vectors (rows or columns) are linearly independent. This is crucial in understanding the solutions to systems of linear equations represented by the matrix.
In simpler terms, it helps in identifying if the given matrix has redundant information or not.


Exercise 4 : Matrix Rank Determination
Instructions
Generate a random 4x4 matrix and find the rank of the matrix.

Expected Output:



Rank: 4


Exercise 5 : Creating Border Array
Instructions
Create a 2D array with 1 on the border and 0 inside.

Expected Output:



array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

Exercise 1: Maximum Value Replacement in Matrix

In [1]:
import numpy as np

# Create a random 5x5 matrix
matrix = np.random.rand(5, 5).round(2)

# Find the maximum value and replace it with 0
max_index = np.unravel_index(np.argmax(matrix), matrix.shape)
matrix[max_index] = 0

print("Modified Matrix:\n", matrix)


Modified Matrix:
 [[0.57 0.56 0.59 0.9  0.  ]
 [0.71 0.65 0.41 0.96 0.75]
 [0.73 0.24 0.82 0.27 0.84]
 [0.08 0.09 0.9  0.26 0.7 ]
 [0.07 0.33 0.3  0.   0.25]]


Exercise 2: Finding Common Values in Arrays

In [2]:
# Create two random arrays of size 5
array1 = np.random.rand(5).round(2)
array2 = np.random.rand(5).round(2)

# Find common values
common = np.intersect1d(array1, array2)

print("Array 1:", array1)
print("Array 2:", array2)
print("Common Values:", common)


Array 1: [0.56 0.41 0.93 0.54 0.49]
Array 2: [0.64 0.89 0.94 0.24 0.34]
Common Values: []


Exercise 3: Sorting Array in Ascending and Descending Order

In [3]:
# Create a random 1D array of size 10
array = np.random.rand(10).round(2)

# Sort ascending and descending
ascending = np.sort(array)
descending = ascending[::-1]

print("Original Array:", array)
print("Ascending:", ascending)
print("Descending:", descending)


Original Array: [0.05 0.95 0.54 0.48 0.82 0.94 0.07 0.13 0.5  0.42]
Ascending: [0.05 0.07 0.13 0.42 0.48 0.5  0.54 0.82 0.94 0.95]
Descending: [0.95 0.94 0.82 0.54 0.5  0.48 0.42 0.13 0.07 0.05]


Exercise 4: Matrix Rank Determination

In [4]:
# Create a random 4x4 matrix
matrix = np.random.rand(4, 4)

# Find matrix rank
rank = np.linalg.matrix_rank(matrix)

print("Matrix:\n", matrix)
print("Rank:", rank)


Matrix:
 [[0.45483567 0.83406859 0.36613886 0.77428783]
 [0.58334025 0.77017523 0.39845271 0.20664763]
 [0.73202927 0.14711334 0.4735121  0.10692871]
 [0.63209359 0.64234497 0.01960349 0.34808155]]
Rank: 4


Exercise 5: Creating Border Array

In [5]:
# Create a 5x5 array with border 1s and inside 0s
border_array = np.ones((5, 5), dtype=int)
border_array[1:-1, 1:-1] = 0

print("Border Array:\n", border_array)


Border Array:
 [[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
